CREATE TABLE `board` (
	`BOARD_NO` INT(11) NOT NULL AUTO_INCREMENT,
	`AD_TITLE` VARCHAR(50) NULL DEFAULT NULL,
	`C_NAME` VARCHAR(20) NULL DEFAULT NULL,
	`INTEREST_CATEGORY` VARCHAR(50) NULL DEFAULT NULL,
	`TARGET` VARCHAR(50) NULL DEFAULT NULL,
	`AD_PERSONNEL` CHAR(3) NULL DEFAULT NULL,
	`AD_START_DATE` DATE NULL DEFAULT NULL,
	`AD_END_DATE` DATE NULL DEFAULT NULL,
	`AD_ANNOUNCEMENT_DATE` DATE NULL DEFAULT NULL,
	`AD_APPLY_TEXT` VARCHAR(200) NULL DEFAULT NULL,
	`C_EMAIL` VARCHAR(30) NULL DEFAULT NULL,
	`AD_AGE` VARCHAR(30) NULL DEFAULT NULL,
	`AD_CHILD` VARCHAR(20) NULL DEFAULT NULL,
	`AD_AREA_NAME` VARCHAR(100) NULL DEFAULT NULL,
	`ONLINE` VARCHAR(100) NULL DEFAULT NULL,
	`AD_TEXT` VARCHAR(200) NULL DEFAULT NULL,
	`WORK_KEYWORD` VARCHAR(100) NULL DEFAULT NULL,
	`WORK_START_DATE` DATE NULL DEFAULT NULL,
	`WORK_END_DATE` DATE NULL DEFAULT NULL,
	`WORK_TIME` VARCHAR(50) NULL DEFAULT NULL,
	`WORK_TEXT` VARCHAR(200) NULL DEFAULT NULL,
	`WORK_BENEFIT_KEY` VARCHAR(50) NULL DEFAULT NULL,
	`WORK_BENEFIT_TEXT` VARCHAR(200) NULL DEFAULT NULL,
	`WORK_TAG` VARCHAR(50) NULL DEFAULT NULL,
	`RECOMMEND_COUNT` INT(11) NULL DEFAULT NULL,
	`VIEW_COUNT` INT(11) NULL DEFAULT NULL,
	`REPORTING_DATE` DATE NOT NULL,
	`URL` VARCHAR(200) NULL DEFAULT NULL,
	PRIMARY KEY (`BOARD_NO`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=16
;
